### ISSUE TITLE
Latest builds not pushed to nginx tag

### ISSUE THREAD

**Issue by michael-os** [coreruleset/modsecurity-crs-docker#44]
According to the Readme in this repo, nginx and 3.3.2-nginx should point to the "last stable ModSecurity v3 on Nginx 1.20 official stable base image, and latest stable Core Rule Set 3.3.2". However, on the Docker hub, the nginx tag was last pushed 8 month ago while v3.3.2-nginx was pushed 2 days ago. This also differs from the apache tag, which indeed gets pushed in sync with the v3.3.2-apache tag.

Furthermore, the specifies 3.3.2-nginx and 3.3.2-apache while on dockerhub the tags are named **v**3.3.2-nginx and **v**3.3.2-apache. It would be great if this could be fixed.

**Comment by franbuehler** [comment]
Thank you @michael-os,

I will have a look at this!!

**Comment by franbuehler** [comment]
Hi @fzipi 
Why do we only tag v3.3.2-apache to apache and not v3.3.2-apache to nginx?
This would resolve this issue here.

https://github.com/coreruleset/modsecurity-crs-docker/blob/master/.github/workflows/buildimage.yml#L33

And do we want to remove the version **v** from the names as the reporter suggested? I'm not sure here.
